[project]
name = "richify"
version = "0.1.0"
description = "Richly render (streamed) markdown, such as from command-line LLMs."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "rich>=13.9.4",
]
